name: 'Build and publish'

on: 
  push:
    branches:
      - main
    paths-ignore: 
      - '**.md'
  pull_request:
    paths-ignore: 
      - '**.md'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set matrix data
        id: set-matrix
        run: echo "matrix=$(jq -c . .versions versions.json)" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Define Docker tag
        shell: bash
        run: |
          echo "NAT_DOCKER_TAG=node-alpine-toobox:${{ matrix }}" >> $GITHUB_ENV
      - name: Build image
        uses: docker/build-push-action@v5
        env: 
          NAT_DOCKER_TAG: ${{ env.NAT_DOCKER_TAG }}
        with:
          push: false
          load: true
          context: .
          file: Dockerfile
          tags: ${{ env.NAT_DOCKER_TAG }}
      - name: Test NPM
        env: 
          NAT_DOCKER_TAG: ${{ env.NAT_DOCKER_TAG }}
        run: docker run --rm ${{ env.NAT_DOCKER_TAG }} npm --version