name: 'Build and publish'

on: 
  push:
    branches:
      - main
    paths-ignore: 
      - '**.md'
  pull_request:
    paths-ignore: 
      - '**.md'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set matrix data
        id: set-matrix
        run: echo "matrix=$(jq -c . < ./matrix.json)" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Define Docker tag
        uses: actions/github-script@v7
        id: docker-tag
        with: 
          result-encoding: string
          script: return "node-alpine-toolbox:${{ matrix.node-version }}"
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          context: .
          build-args: "NODE_VERSION=${{ matrix.node-version }}"
          file: Dockerfile
          tags: ${{ steps.docker-tag.outputs.result }}
      - name: Test NPM
        env: 
          NAT_DOCKER_TAG: ${{ steps.docker-tag.outputs.result }}
        run: docker run --rm ${{ steps.docker-tag.outputs.result }} npm --version