name: 'Build and publish'

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore: 
      - '**.md'
  pull_request:
    paths-ignore: 
      - '**.md'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set matrix data
        id: set-matrix
        run: echo "matrix=$(jq -c . < ./matrix.json)" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Define Docker tag
        uses: actions/github-script@v7
        id: docker-tag
        with: 
          result-encoding: string
          script: return "octopixell/node-alpine-toolbox:node-${{ matrix.node-version }}"
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          build-args: "NODE_VERSION=${{ matrix.node-version }}"
          tags: ${{ steps.docker-tag.outputs.result }}
      - name: Test NPM
        env: 
          NAT_DOCKER_TAG: ${{ steps.docker-tag.outputs.result }}
        run: docker run --rm ${{ steps.docker-tag.outputs.result }} npm --version
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: "NODE_VERSION=${{ matrix.node-version }}"
          tags: ${{ steps.docker-tag.outputs.result }}
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x